### ISSUE TITLE
Si vas muy rápido atravesas las paredes.

### ISSUE THREAD

**Issue by PlayJamDevs** [PlayJamDevs/playjamgames#4]
@Streq Hay un pequeño bug, nada que rompa el juego, que si vas muy rápido atravesas las paredes. Por suerte lo toma cómo que perdés.

_Originally posted by @PlayJamDevs in https://github.com/PlayJamDevs/playjamgames/issues/3#issuecomment-1263067040_

**Comment by PlayJamDevs** [comment]
@Streq

**Comment by Streq** [comment]
Puede que sea la lógica de estrellarse, no se nota porque no hay señalización de derrota, sólo se cierra el juego, pero si el canario vuela muy rápido y choca con una pared estalla en muchas plumas, si es contra una pared del borde de la pantalla no se ven las plumas porque por inercia salen de la pantalla.

**Comment by Streq** [comment]
Queda pendiente cambiarlo para dar una señal más clara al jugador
